pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        //GradleビルドスクリプトにおいてリポジトリとしてJitPackを追加するための宣言
        //JitPackは、GitHub上の公開されたGitリポジトリから直接依存関係をビルドして提供するサービス
    }
}
rootProject.name = "QuizVoyageMath"
include ':app'
